//Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_SALES = 'PRODUCT_SALES';
export const PRODUCT_OUT_OF_STOCKS = 'PRODUCT_OUT_OF_STOCKS';

//Services
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICE = 'GET_SERVICE';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const SERVICE_SALES = 'SERVICE_SALES';

//Shops
export const GET_SHOPS = 'GET_SHOPS';
export const GET_SHOP = 'GET_SHOP';
export const CREATE_SHOP = 'CREATE_SHOP';
export const UPDATE_SHOP = 'UPDATE_SHOP';
export const DELETE_SHOP = 'DELETE_SHOP';
export const SHOP_SALES = 'SHOP_SALES';

//Assistants
export const GET_ASSISTANTS = 'GET_ASSISTANTS';
export const GET_ASSISTANT = 'GET_ASSISTANT';
export const CREATE_ASSISTANT = 'CREATE_ASSISTANT';
export const UPDATE_ASSISTANT = 'UPDATE_ASSISTANT';
export const DELETE_ASSISTANT = 'DELETE_ASSISTANT';
export const ASSISTANT_SALES = 'ASSISTANT_SALES';
export const BEST_ASSISTANT_SALE = 'BEST_ASSISTANT_SALE';
export const WORST_ASSISTANT_SALE = 'WORST_ASSISTANT_SALE'

//Customers
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

//Orders
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER = 'GET_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';